language: python

install:
    - pip install -r requirements.txt
    - stat /tmp/modelsim_ase || (curl 'http://download.altera.com/akdlm/software/acdsinst/19.1std/670/ib_installers/ModelSimSetup-19.1.0.670-linux.run' -o ModelSimSetup.run && chmod +x ModelSimSetup.run && ./ModelSimSetup.run --mode unattended --accept_eula 1 --installdir /tmp && sed -i 's/linux_rh60/linuxaloem/g' /tmp/modelsim_ase/vco )
    - find /tmp/modelsim_ase
script:
    - export PATH=$PATH:/tmp/modelsim_ase/linuxaloem
    - cd ./sim/modelsim/top_tb/
    - hdlmake
    - make clean
    - make

