sudo: required
language: python
os: linux
addons:
  apt:
    update: false
    packages:
      - gcc-multilib
      - lib32gcc1
      - lib32z1
      - lib32stdc++6
      - g++-multilib

install:
    - pip install -r requirements.txt
    - stat /tmp/modelsim_ase || (curl 'http://download.altera.com/akdlm/software/acdsinst/19.1std/670/ib_installers/ModelSimSetup-19.1.0.670-linux.run' -o ModelSimSetup.run && chmod +x ModelSimSetup.run && ./ModelSimSetup.run --mode unattended --accept_eula 1 --installdir /tmp && sed -i 's/linux_rh60/linux/g' /tmp/modelsim_ase/vco )
script:
    - export PATH=$PATH:/tmp/modelsim_ase/bin
    - cd ./sim/modelsim/top_tb/
    - hdlmake fetch
    - hdlmake
    - make clean
    - make

